cap nhat thong ke cho admin

diff --git a/foodnow/.github/workflows/run_cloud.yaml b/foodnow/.github/workflows/run_cloud.yaml
--- a/foodnow/.github/workflows/run_cloud.yaml
+++ b/foodnow/.github/workflows/run_cloud.yaml
@@ -1,77 +1,77 @@
-name: CI/CD Deploy to EC2
-
-
-on:
-  push:
-    branches:
-      - develop
-jobs:
-  deploy:
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout source code
-        uses: actions/checkout@v4
-
-      - name: Add SSH key
-        uses: webfactory/ssh-agent@v0.9.0
-        with:
-          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
-
-      - name: Compress source code
-        run: |
-          tar --exclude=app.tar.gz \
-              --exclude=__pycache__ \
-              --exclude=.git \
-              --exclude=node_modules \
-              --ignore-failed-read \
-              --czf app.tar.gz .
-      - name: Copy code to EC2
-        env:
-          HOST: ${{ secrets.VM_HOST }}
-          USER: ${{ secrets.VM_USER }}
-          PORT: ${{ secrets.VM_PORT }}
-        run: |
-          scp -o StrictHostKeyChecking=no -p $PORT app.tar.gz $USER@$HOST:/home/$USER/app.tar.gz
-
-      - name: Deploy on EC2
-        env:
-          HOST: ${{ secrets.VM_HOST }}
-          USER: ${{ secrets.VM_USER }}
-          PORT: ${{ secrets.VM_PORT }}
-        run: |
-          ssh -o StrictHostKeyChecking=no -p $PORT $USER@$HOST "
-            # cai dat docker neu chua co
-            if ! command -v docker &>/dev/null; then
-               sudo apt-get update
-               sudo apt-get install -y docker.io
-               sudo systemctl enable docker
-               sudo systemctl start docker
-            fi
-            # cai dock-compose neu chua co
-            if ! command -v docker-compose &>/dev/null && ! docker compose version &>/dev/null; then
-               sudo apt-get update
-               sudo apt-get install -y docker-compose-plugin || \
-               (sudo curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose)
-            fi
-            
-            # add user vao nhom docker
-            sudo usermod -aG docker ubuntu
-            
-            
-            # ghi dung dinh dang sudoers de tranh hong sudo
-            echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/ubuntu
-          
-            # tao thu muc va giai nen ma nguon
-            mkdir -p /home/ubuntu/IndustryProject
-            tar xzf /home/ubuntu/app.tar.gz -C /home/ubuntu/IndustryProject --strip-components=1
-            rm home/ubuntu/app.tar.gz
-            cd home/ubuntu/IndustryProject
-          
-            # chay docker compose
-            if command -v docker-compose &>/dev/null; then
-                sudo docker-compose up -d build
-            else 
-                sudo docker-compose up -d build
-            fi
-         "
+#name: CI/CD Deploy to EC2
+#
+#
+#on:
+#  push:
+#    branches:
+#      - develop
+#jobs:
+#  deploy:
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#      - name: Checkout source code
+#        uses: actions/checkout@v4
+#
+#      - name: Add SSH key
+#        uses: webfactory/ssh-agent@v0.9.0
+#        with:
+#          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+#
+#      - name: Compress source code
+#        run: |
+#          tar --exclude=app.tar.gz \
+#              --exclude=__pycache__ \
+#              --exclude=.git \
+#              --exclude=node_modules \
+#              --ignore-failed-read \
+#              --czf app.tar.gz .
+#      - name: Copy code to EC2
+#        env:
+#          HOST: ${{ secrets.VM_HOST }}
+#          USER: ${{ secrets.VM_USER }}
+#          PORT: ${{ secrets.VM_PORT }}
+#        run: |
+#          scp -o StrictHostKeyChecking=no -p $PORT app.tar.gz $USER@$HOST:/home/$USER/app.tar.gz
+#
+#      - name: Deploy on EC2
+#        env:
+#          HOST: ${{ secrets.VM_HOST }}
+#          USER: ${{ secrets.VM_USER }}
+#          PORT: ${{ secrets.VM_PORT }}
+#        run: |
+#          ssh -o StrictHostKeyChecking=no -p $PORT $USER@$HOST "
+#            # cai dat docker neu chua co
+#            if ! command -v docker &>/dev/null; then
+#               sudo apt-get update
+#               sudo apt-get install -y docker.io
+#               sudo systemctl enable docker
+#               sudo systemctl start docker
+#            fi
+#            # cai dock-compose neu chua co
+#            if ! command -v docker-compose &>/dev/null && ! docker compose version &>/dev/null; then
+#               sudo apt-get update
+#               sudo apt-get install -y docker-compose-plugin || \
+#               (sudo curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose)
+#            fi
+#
+#            # add user vao nhom docker
+#            sudo usermod -aG docker ubuntu
+#
+#
+#            # ghi dung dinh dang sudoers de tranh hong sudo
+#            echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/ubuntu
+#
+#            # tao thu muc va giai nen ma nguon
+#            mkdir -p /home/ubuntu/IndustryProject
+#            tar xzf /home/ubuntu/app.tar.gz -C /home/ubuntu/IndustryProject --strip-components=1
+#            rm home/ubuntu/app.tar.gz
+#            cd home/ubuntu/IndustryProject
+#
+#            # chay docker compose
+#            if command -v docker-compose &>/dev/null; then
+#                sudo docker-compose up -d build
+#            else
+#                sudo docker-compose up -d build
+#            fi
+#         "
